# Reference:
# 1. https://github.com/actions/starter-workflows/blob/main/deployments/azure-webapps-node.yml
name: Deploy for release versions

on:
  push:
    branches:
      - main # Deploy when code is pushed to 'main'

env:
  WEBAPP_NAME: ECOTEL_QL_LENH_SX # set this to your application's name
  WEBAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: "20.x" # set this to the node version to use

# permissions:
#   contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Working Directory
        run: pwd

      - name: Create an .env file in frontend for building image
        run: |
          echo "VITE_BASE_API=${{ secrets.VITE_BASE_API }}" > ./WebApp/Frontend/.env
          echo "VITE_SOCKET_API=${{ secrets.VITE_SOCKET_API_RELEASE }}" >> ./WebApp/Frontend/.env
          echo "VITE_MAP_API_KEY=${{ secrets.VITE_MAP_API_KEY }}" >> ./WebApp/Frontend/.env

      - name: List Files
        run: ls -laR

      - name: Run Makefiles with Secrets to build anh push docker images to dockerhub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          cd WebApp
          make release
          cd ../
          ls -al WebApp/.env
          cat WebApp/.env
          cp WebApp/.env deployment/release/

      - name: Ensure target directory exists
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.RELEASE_HOST }}
          username: ${{ secrets.RELEASE_USER }}
          key: ${{ secrets.RELEASE_SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.RELEASE_USER }}/ecotel_ktv/deployment/release

      - name: Transfer docker-compose file to VPS for deployment
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.RELEASE_HOST }}
          username: ${{ secrets.RELEASE_USER }}
          key: ${{ secrets.RELEASE_SSH_KEY }}
          source: "deployment/release/*"
          target: "/home/${{ secrets.RELEASE_USER }}/ecotel_ktv/deployment/release"
          strip_components: 2 # Removes "deployment/release/" folder path!

      - name: Clean up containers and stuff via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.RELEASE_HOST }}
          username: ${{ secrets.RELEASE_USER }}
          key: ${{ secrets.RELEASE_SSH_KEY }}
          script: |
            # Change to release deployment directory
            cd /home/${{ secrets.RELEASE_USER }}/ecotel_ktv/deployment/release 
            # Debug info
            pwd
            ls -al
            docker image prune -f
            docker compose -f release-docker-compose.yaml down # always down first
            docker ps

      - name: Deploy to release via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.RELEASE_HOST }}
          username: ${{ secrets.RELEASE_USER }}
          key: ${{ secrets.RELEASE_SSH_KEY }}
          script: |
            ### Change to release deployment directory
            cd /home/${{ secrets.RELEASE_USER }}/ecotel_ktv/deployment/release 
            ### Clean up unused images
            docker image prune -f # clean up unused images
            ### Provide permissions and start the application
            chmod +x start-app.sh
            ./start-app.sh
